### ISSUE TITLE
Too many macros

### ISSUE THREAD

**Issue by chakravala** [Keno/InterfaceSpecs.jl#1]
While interesting ideas are pursued, lost in thought, you fell in the trap of using macros for everything. There are other paradigms of thinking that should be explored before a whole collection of macros might be introduced. At least that's how it is in my pursuit.

**Comment by Keno** [comment]
_Aroden then took off the mask and revealed his face. 'Your appearance matters not,' he said. 'Only the truth of spirit in your heart'._

The macros are just there to play with syntax options. The only thing that is given semantic meaning is the forall intrinsics.
